package elovaire.music.droidbeauty.app.quality

import elovaire.music.droidbeauty.app.ui.screens.RootRouteRegistry

internal enum class RapidUiSurfaceKind {
    Route,
    FullScreenLayer,
    Chrome,
    Popup,
    Dialog,
    Sheet,
    Mode,
    SystemUi,
}

internal data class RapidUiSurface(
    val id: String,
    val kind: RapidUiSurfaceKind,
    val entryJourney: String,
    val exitJourney: String,
    val routePattern: String? = null,
    val requiresDeterministicContent: Boolean = false,
    val involvesSystemUi: Boolean = false,
)

/**
 * Test-only coverage inventory. It is intentionally data rather than a navigation abstraction:
 * adding a route or a stateful interaction surface requires an explicit qualification entry.
 */
internal object RapidUiSurfaceCatalog {
    val routes: List<RapidUiSurface> = listOf(
        route("route.home", RootRouteRegistry.HOME, "cold start or Home", "Back or another tab"),
        route("route.albums", RootRouteRegistry.ALBUMS, "Albums tab", "Back or another tab"),
        route("route.recently_added", RootRouteRegistry.RECENTLY_ADDED, "Albums > Recently added", "Back"),
        route("route.audiobooks", RootRouteRegistry.AUDIOBOOKS, "Albums > Audiobooks", "Back"),
        route("route.audiobook_detail", RootRouteRegistry.AUDIOBOOK, "Audiobooks > book", "Back"),
        route("route.audiobook_tag_editor", RootRouteRegistry.AUDIOBOOK_TAG_EDITOR, "Audiobook > Edit tags", "Save or Back"),
        route("route.playlists", RootRouteRegistry.PLAYLISTS, "Playlists tab", "Back or another tab"),
        route("route.search", RootRouteRegistry.SEARCH, "Search tab", "Back or another tab"),
        route("route.playlist_detail", RootRouteRegistry.PLAYLIST, "Playlists > playlist", "Back"),
        route("route.smart_playlist_detail", RootRouteRegistry.SMART_PLAYLIST, "Playlists > smart playlist", "Back"),
        route("route.smart_playlist_create", RootRouteRegistry.SMART_PLAYLIST_EDITOR, "Create smart playlist", "Save or Back"),
        route("route.smart_playlist_edit", RootRouteRegistry.SMART_PLAYLIST_EDITOR_EXISTING, "Smart playlist > Edit", "Save or Back"),
        route("route.album_detail", RootRouteRegistry.ALBUM, "Albums > album", "Back"),
        route("route.album_tag_editor", RootRouteRegistry.ALBUM_TAG_EDITOR, "Album > Edit tags", "Save or Back"),
        route("route.library_collection", RootRouteRegistry.LIBRARY_COLLECTION, "Albums > collection", "Back"),
        route("route.genre_detail", RootRouteRegistry.GENRE, "Albums > genre", "Back"),
        route("route.artist_detail", RootRouteRegistry.ARTIST, "Albums > artist", "Back"),
        route("route.equalizer", RootRouteRegistry.EQUALIZER, "Menu > Equalizer", "Back"),
        route("route.crossfade", RootRouteRegistry.CROSSFADE, "Settings > Crossfade", "Back"),
        route("route.audiobook_settings", RootRouteRegistry.AUDIOBOOK_SETTINGS, "Settings > Audiobook", "Back"),
        route("route.settings", RootRouteRegistry.SETTINGS, "Menu > Settings", "Back"),
        route("route.manage_playlists", RootRouteRegistry.MANAGE_PLAYLISTS, "Settings > Manage playlists", "Back"),
        route("route.library_folders", RootRouteRegistry.LIBRARY_FOLDERS, "Settings > Library folders", "Back"),
        route("route.now_playing_bar_style", RootRouteRegistry.NOW_PLAYING_BAR_STYLE, "Settings > Now Playing bar", "Back"),
        route("route.smart_playlist_settings", RootRouteRegistry.SMART_PLAYLIST_SETTINGS, "Settings > Smart playlists", "Back"),
        route("route.changelog", RootRouteRegistry.CHANGELOG, "Menu > Changelog", "Back"),
        route("route.about", RootRouteRegistry.ABOUT, "Settings > About", "Back"),
        route("route.privacy_policy", RootRouteRegistry.PRIVACY_POLICY, "Settings > Privacy", "Back"),
    )

    val transientLayers: List<RapidUiSurface> = listOf(
        surface("root.permission_gate", RapidUiSurfaceKind.FullScreenLayer, "cold start", "grant, deny, or Back", systemUi = true),
        surface("root.permission_loading", RapidUiSurfaceKind.FullScreenLayer, "permission result", "completion or cancellation"),
        surface("root.top_bar", RapidUiSurfaceKind.Chrome, "any route", "route change"),
        surface("root.top_bar_menu", RapidUiSurfaceKind.Popup, "top-bar Menu", "select, outside tap, or Back"),
        surface("root.changelog_sheet", RapidUiSurfaceKind.Sheet, "root changelog action", "close, scrim, or Back"),
        surface("root.create_playlist_dialog", RapidUiSurfaceKind.Dialog, "create playlist", "create, cancel, or Back"),
        surface("root.update_dialog", RapidUiSurfaceKind.Dialog, "update available", "action, cancel, or Back"),
        surface("root.bottom_navigation", RapidUiSurfaceKind.Chrome, "any top-level route", "route change"),
        surface("root.compact_player", RapidUiSurfaceKind.Chrome, "active playback", "expand, minimize, or route change"),
        surface("root.full_player", RapidUiSurfaceKind.FullScreenLayer, "compact player", "minimize, Back, or route action"),
        surface("root.scrim", RapidUiSurfaceKind.Chrome, "blocking root layer", "dismissed layer"),
        surface("common.sort_options", RapidUiSurfaceKind.Popup, "sort action", "select, outside tap, or Back"),
        surface("common.fast_scrollbar", RapidUiSurfaceKind.Mode, "scrollable list", "release or route change"),
        surface("library.selection", RapidUiSurfaceKind.FullScreenLayer, "long-press library item", "Back or action completion"),
        surface("library.selection_menu", RapidUiSurfaceKind.Popup, "selected library items", "select action or dismiss"),
        surface("library.add_to_playlist", RapidUiSurfaceKind.Dialog, "selection action", "choose playlist or dismiss"),
        surface("library.delete_selected_media", RapidUiSurfaceKind.SystemUi, "selection delete action", "approve, deny, or cancel", systemUi = true),
        surface("library.album_modes", RapidUiSurfaceKind.Mode, "album layout control", "switch mode or route change"),
        surface("library.song_modes", RapidUiSurfaceKind.Mode, "song layout control", "switch mode or route change"),
        surface("library.collection.songs", RapidUiSurfaceKind.Mode, "Albums > Songs", "Back"),
        surface("library.collection.albums", RapidUiSurfaceKind.Mode, "Albums > Albums", "Back"),
        surface("library.collection.artists", RapidUiSurfaceKind.Mode, "Albums > Artists", "Back"),
        surface("library.collection.genres", RapidUiSurfaceKind.Mode, "Albums > Genres", "Back"),
        surface("library.collection.compact", RapidUiSurfaceKind.Mode, "collection layout control", "switch mode or route change"),
        surface("library.collection.grid", RapidUiSurfaceKind.Mode, "collection layout control", "switch mode or route change"),
        surface("library.collection.dense_grid", RapidUiSurfaceKind.Mode, "collection layout control", "switch mode or route change"),
        surface("library.album_overflow", RapidUiSurfaceKind.Popup, "album overflow", "select or dismiss"),
        surface("library.song_overflow", RapidUiSurfaceKind.Popup, "song overflow", "select or dismiss"),
        surface("library.playback_artwork", RapidUiSurfaceKind.Chrome, "playing row", "playback change"),
        surface("library.favorite_toggle", RapidUiSurfaceKind.Mode, "favorite action", "toggle"),
        surface("library.artist_gallery", RapidUiSurfaceKind.Mode, "artist detail", "scroll or Back"),
        surface("library.recently_added_search", RapidUiSurfaceKind.Mode, "Recently added", "clear or Back"),
        surface("audiobooks.selection", RapidUiSurfaceKind.FullScreenLayer, "long-press audiobook", "Back or action completion"),
        surface("audiobooks.add_to_playlist", RapidUiSurfaceKind.Dialog, "audiobook selection action", "choose or dismiss"),
        surface("audiobooks.collection_modes", RapidUiSurfaceKind.Mode, "audiobook layout control", "switch mode or route change"),
        surface("audiobooks.collection_compact", RapidUiSurfaceKind.Mode, "audiobook layout control", "switch mode or route change"),
        surface("audiobooks.collection_grid", RapidUiSurfaceKind.Mode, "audiobook layout control", "switch mode or route change"),
        surface("audiobooks.collection_dense_grid", RapidUiSurfaceKind.Mode, "audiobook layout control", "switch mode or route change"),
        surface("audiobooks.play_resume_again", RapidUiSurfaceKind.Mode, "audiobook detail", "play, resume, or play again"),
        surface("audiobooks.start_over", RapidUiSurfaceKind.Mode, "audiobook detail", "start over"),
        surface("audiobooks.description_preview", RapidUiSurfaceKind.Mode, "audiobook detail", "expand description"),
        surface("audiobooks.description_dialog", RapidUiSurfaceKind.Dialog, "description MORE", "close, scrim, or Back"),
        surface("audiobooks.chapter_rows", RapidUiSurfaceKind.Mode, "audiobook detail", "scroll or chapter action"),
        surface("playlists.selection", RapidUiSurfaceKind.FullScreenLayer, "long-press playlist", "Back or action completion"),
        surface("playlists.create_dialog", RapidUiSurfaceKind.Dialog, "new playlist", "create, cancel, or Back"),
        surface("playlists.rename_dialog", RapidUiSurfaceKind.Dialog, "playlist rename", "save, cancel, or Back"),
        surface("playlists.add_songs", RapidUiSurfaceKind.Dialog, "playlist add songs", "choose songs or dismiss"),
        surface("playlists.overflow", RapidUiSurfaceKind.Popup, "playlist overflow", "select or dismiss"),
        surface("playlists.delete_confirmation", RapidUiSurfaceKind.Dialog, "playlist delete", "confirm, cancel, or Back"),
        surface("playlists.smart_rule_editor", RapidUiSurfaceKind.Mode, "smart playlist editor", "add, remove, edit, or Back"),
        surface("playlists.smart_rule_type", RapidUiSurfaceKind.Popup, "smart rule type", "select or dismiss"),
        surface("playlists.smart_rule_value", RapidUiSurfaceKind.Mode, "smart rule value", "input or Back"),
        surface("playlists.inline_creator", RapidUiSurfaceKind.Dialog, "inline create playlist", "create or dismiss"),
        surface("search.discover", RapidUiSurfaceKind.Mode, "Search tab", "enter query or Back"),
        surface("search.query_input", RapidUiSurfaceKind.Mode, "Search tab", "type, clear, or IME Back"),
        surface("search.history", RapidUiSurfaceKind.Mode, "empty query", "select or clear history"),
        surface("search.quick_picks", RapidUiSurfaceKind.Mode, "empty query", "select or Back"),
        surface("search.category_grids", RapidUiSurfaceKind.Mode, "search results", "open category or Back"),
        surface("search.result_sort", RapidUiSurfaceKind.Popup, "result sort", "select or dismiss"),
        surface("settings.theme", RapidUiSurfaceKind.Dialog, "theme row", "choose or dismiss"),
        surface("settings.text_size", RapidUiSurfaceKind.Mode, "text-size controls", "change and route away"),
        surface("settings.language", RapidUiSurfaceKind.Dialog, "language row", "choose or dismiss"),
        surface("settings.toggles", RapidUiSurfaceKind.Mode, "settings toggles", "toggle and re-enter"),
        surface("settings.library_scan", RapidUiSurfaceKind.Mode, "scan library", "completion or route change"),
        surface("folders.source_chooser", RapidUiSurfaceKind.Sheet, "Add library folder", "choose or dismiss"),
        surface("folders.network_editor", RapidUiSurfaceKind.Dialog, "network source", "save, cancel, or Back"),
        surface("folders.protocol_mode", RapidUiSurfaceKind.Mode, "network source editor", "switch SMB/WebDAV"),
        surface("folders.remove_confirmation", RapidUiSurfaceKind.Dialog, "remove source", "confirm or cancel"),
        surface("folders.probe_state", RapidUiSurfaceKind.Mode, "network save/probe", "completion or route change"),
        surface("manage_playlists.empty", RapidUiSurfaceKind.Mode, "manage playlists", "route change"),
        surface("manage_playlists.populated", RapidUiSurfaceKind.Mode, "manage playlists", "export/import"),
        surface("manage_playlists.create_document", RapidUiSurfaceKind.SystemUi, "export", "cancel or result", systemUi = true),
        surface("manage_playlists.open_document", RapidUiSurfaceKind.SystemUi, "import", "cancel or result", systemUi = true),
        surface("tag.album_fields", RapidUiSurfaceKind.Mode, "album tag editor", "input, save, or Back"),
        surface("tag.album_track_fields", RapidUiSurfaceKind.Mode, "album tag editor", "scroll and input"),
        surface("tag.audiobook_fields", RapidUiSurfaceKind.Mode, "audiobook tag editor", "input, save, or Back"),
        surface("tag.artwork_picker", RapidUiSurfaceKind.SystemUi, "artwork action", "cancel or result", systemUi = true),
        surface("tag.mediastore_write", RapidUiSurfaceKind.SystemUi, "tag save", "grant, deny, or cancellation", systemUi = true),
        surface("tag.saf_write", RapidUiSurfaceKind.SystemUi, "tag save", "grant, deny, or cancellation", systemUi = true),
        surface("equalizer.graph", RapidUiSurfaceKind.Mode, "Equalizer", "scroll, drag, or Back"),
        surface("equalizer.bands", RapidUiSurfaceKind.Mode, "Equalizer", "band adjustment"),
        surface("equalizer.bass", RapidUiSurfaceKind.Mode, "Equalizer", "drag or tap"),
        surface("equalizer.midrange", RapidUiSurfaceKind.Mode, "Equalizer", "drag or tap"),
        surface("equalizer.treble", RapidUiSurfaceKind.Mode, "Equalizer", "drag or tap"),
        surface("equalizer.spaciousness", RapidUiSurfaceKind.Mode, "Equalizer", "mode and strength"),
        surface("equalizer.reverb", RapidUiSurfaceKind.Mode, "Equalizer", "profile, duration, reset"),
        surface("equalizer.presets", RapidUiSurfaceKind.Popup, "Equalizer", "select or dismiss"),
        surface("crossfade.controls", RapidUiSurfaceKind.Mode, "Crossfade", "toggle, adjust, or Back"),
        surface("audiobook_settings.controls", RapidUiSurfaceKind.Mode, "Audiobook settings", "step controls and Back"),
        surface("smart_playlist_settings.controls", RapidUiSurfaceKind.Mode, "Smart playlist settings", "toggle, adjust, or Back"),
        surface("now_playing_style.options", RapidUiSurfaceKind.Mode, "Now Playing bar style", "select and re-enter"),
        surface("changelog.full_screen", RapidUiSurfaceKind.Mode, "Changelog route", "Back"),
        surface("about.links", RapidUiSurfaceKind.Mode, "About route", "open intent or Back"),
        surface("privacy.scroll", RapidUiSurfaceKind.Mode, "Privacy route", "scroll or Back"),
        surface("player.transport", RapidUiSurfaceKind.Mode, "full player", "play, previous, next"),
        surface("player.gesture", RapidUiSurfaceKind.FullScreenLayer, "compact player", "expand, reverse, or release"),
        surface("player.seek", RapidUiSurfaceKind.Mode, "full player", "drag or release"),
        surface("player.volume", RapidUiSurfaceKind.Mode, "full player", "drag or tap"),
        surface("player.queue", RapidUiSurfaceKind.Sheet, "full player Queue", "item, reorder, or Back"),
        surface("player.queue_overflow", RapidUiSurfaceKind.Popup, "queue item overflow", "select or dismiss"),
        surface("player.lyrics_loading", RapidUiSurfaceKind.Mode, "full player Lyrics", "wait or Back"),
        surface("player.lyrics_ready", RapidUiSurfaceKind.Mode, "full player Lyrics", "scroll and seek"),
        surface("player.lyrics_unavailable", RapidUiSurfaceKind.Mode, "full player Lyrics", "Back"),
        surface("player.lyrics_editor", RapidUiSurfaceKind.Mode, "edit lyrics", "save, cancel, or Back"),
        surface("player.lyrics_write", RapidUiSurfaceKind.SystemUi, "save embedded lyrics", "approve, deny, or cancel", systemUi = true),
        surface("player.sleep_timer", RapidUiSurfaceKind.Dialog, "sleep timer", "select, reset, or dismiss"),
        surface("player.song_overflow", RapidUiSurfaceKind.Popup, "song overflow", "select or dismiss"),
        surface("player.album_overflow", RapidUiSurfaceKind.Popup, "album overflow", "select or dismiss"),
        surface("player.equalizer_shortcut", RapidUiSurfaceKind.Mode, "player Equalizer", "route change"),
    )

    val all: List<RapidUiSurface> = routes + transientLayers

    val routePatterns: Set<String>
        get() = routes.mapNotNull { it.routePattern }.toSet()

    val ids: Set<String>
        get() = all.map { it.id }.toSet()

    private fun route(
        id: String,
        pattern: String,
        entry: String,
        exit: String,
    ): RapidUiSurface = RapidUiSurface(
        id = id,
        kind = RapidUiSurfaceKind.Route,
        entryJourney = entry,
        exitJourney = exit,
        routePattern = pattern,
        requiresDeterministicContent = true,
    )

    private fun surface(
        id: String,
        kind: RapidUiSurfaceKind,
        entry: String,
        exit: String,
        systemUi: Boolean = false,
    ): RapidUiSurface = RapidUiSurface(
        id = id,
        kind = kind,
        entryJourney = entry,
        exitJourney = exit,
        requiresDeterministicContent = kind != RapidUiSurfaceKind.Chrome,
        involvesSystemUi = systemUi,
    )
}
